import React, { Children, ReactNode } from 'react'
import StreamVideoProvider from '@/providers/StreamClientProvider'
import AuthGuard from '@/components/AuthGuard'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "ZinkUp",
  description: "Generated by create next app",
  icons:{
    icon: '/icons/logo.svg'
  }
};

const RootLayout= ({children}: {children: ReactNode}) => {
  return (
    <AuthGuard>
      <div>
        <main>
          <StreamVideoProvider>
          {children}
          </StreamVideoProvider>
        </main>
      </div>
    </AuthGuard>
  )
}

export default RootLayout

