import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import CSSImports from "@/components/CSSImports";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZinkUp",
  description: "Generated by create next app",
  icons:{
    icon: '/icons/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark2`}>
        <ClerkProvider
          appearance={{
            layout: {
              logoImageUrl: '/icons/logo.png',
              socialButtonsVariant: 'iconButton'
            },
            variables: {
              colorText: '#fff',
              colorPrimary: '#2c4fa8',
              colorBackground: '#1c1f2e',
              colorInputBackground: '#161925',
              colorInputText: '#fff'
            }
          }}
        >
          <CSSImports />
          {children}
          <Toaster position="top-right" richColors closeButton />
        </ClerkProvider>
      </body>
    </html>
  );
}
